remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: "Specmatic"
latest_release: 0.57.0

spec_cmd: "java -jar /path/to/specmatic.jar"

aux_links:
  "Specmatic on GitHub":
    - "//github.com/znsio/specmatic"

plugins:
  - jekyll-remote-theme

logo: "/images/specmatic-logo.png"

