remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: "Specmatic"
latest_release: 0.71.0
jms_release: 0.1.0
kafka_release: 0.4.0
db_release: 0.61.8-db

spec_cmd: "java -jar /path/to/specmatic.jar"

aux_links:
  "Specmatic on GitHub":
    - "//github.com/znsio/specmatic"

plugins:
  - jekyll-remote-theme

logo: "/images/specmatic-logo.png"

