remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: "Qontract"
latest_release: 0.7.0

aux_links:
  "Qontract on GitHub":
    - "//github.com/qontract/qontract"

plugins:
  - jekyll-remote-theme
