remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: "Specmatic"
latest_release: 1.2.23
jms_release: 0.1.0
kafka_release: 0.4.0
db_release: 0.61.8-db
redis_release: 0.9.0

spec_cmd: "java -jar /path/to/specmatic.jar"

aux_links:
  "Specmatic on GitHub":
    - "//github.com/znsio/specmatic"

plugins:
  - jekyll-remote-theme
  - jekyll-tabs

logo: "/images/specmatic-logo.png"

exclude:
  - archive
