remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: "Specmatic"
latest_release: 0.26.1

qontract_cmd: "java -jar /path/to/specmatic"

aux_links:
  "Specmatic on GitHub":
    - "//github.com/znsio/specmatic"

plugins:
  - jekyll-remote-theme

logo: "/images/specmatic-logo.png"
